import type { NextPage } from "next";
import Head from "next/head";
import Publication from "../components/Publications";
import Search from "../components/Search";
import PoolStat from "../components/Stats/PoolStat";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Encode Dao Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-4 px-2 sm:px-4 py-2.5">
        <div>
          <PoolStat />
        </div>
        <div className="lg:col-span-3">
          <Search />
          <Publication />
        </div>
      </div>
    </div>
  );
};

export default Home;
